# Server Configuration
server.port=8082

# CORS Configuration
spring.mvc.cors.allowed-origins=http://localhost:3005
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*
spring.mvc.cors.allow-credentials=true

# Logging Configuration
logging.level.org.springframework.web=DEBUG
logging.level.com.borsvy=DEBUG

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/borsvy
spring.datasource.username=postgres
spring.datasource.password=7054
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool Settings
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.connection-test-query=SELECT 1

# Error Handling
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.zaxxer.hikari=DEBUG

# Finnhub API Configuration
finnhub.api.key=cvgbp21r01qqg993ib10cvgbp21r01qqg993ib1g
finnhub.api.url=https://finnhub.io/api/v1
